# Generated by Django 4.2.3 on 2023-07-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
